build:
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-html target/coverage
            coverage:
              file: target/coverage
              format: clover
